version: '3'

#Define services/containers to be run
services:
  client: #Name of the first service!
    restart: always
    build: client # Specify directory of the Dockerfile
    ports:
     - "3000:80" # Specify port mapping
    links:
     - server

  server: #Name of the second service
    restart: always
    build: server
    ports:
     - "4000:4000"